#!/bin/sh

FILE=$1
PFX=`echo $FILE | sed 's/\..*//g'`

I=1

function mask {
  MASK="$PFX"_mask_"$I".png
  I=$(expr $I + 1)
  NEXT_MASK="$PFX"_mask_"$I".png

}
mask

cp $FILE $MASK
convert -black-threshold 2% $MASK $NEXT_MASK

mask
convert-magicwand 1,1 -t 2 -f mask -m binary -r inside $MASK $NEXT_MASK

mask
convert -negate $MASK $NEXT_MASK

mask
convert -virtual-pixel edge -blur 100% $MASK $NEXT_MASK

mask
convert $FILE -alpha Off $MASK -compose CopyOpacity -composite PNG32:"$PFX"_alpha.png


convert -fuzz 15% -trim +repage "$PFX"_alpha.png alpha2/$FILE

rm "$PFX"_mask* "$PFX"_alpha.png
