#!/bin/sh

FILE=$1
PFX=`echo $FILE | sed 's/\..*//g'`

convert -background none -compose SrcOver -flatten $FILE composite2.png corner/$FILE
convert -background none -compose Xor -flatten corner/$FILE composite2.png corner/$FILE
