#!/bin/sh

#. ~/.xinitrc
#xinput --list
#xinput --query-state "Logitech USB Trackball"
xinput --set-button-map "Logitech USB Trackball" 1 8 3 4 5 6 7 2 9



#  two fingers up - 4
#   down - 5
#  left - 6
#  right - 7
#
xinput --set-button-map "ETPS/2 Elantech Touchpad" 1 3 2



